[package]
name = "eventfd"
version = "0.2.0"
authors = ["Jeremy Fitzhardinge <jeremy@goop.org>"]
description = "Binding to Linux's eventfd syscall"
repository = "https://github.com/jsgf/eventfd-rust.git"
readme = "README.md"
license = "MIT"
edition = "2021"

[dependencies]
nix = "0.24"
